name: dev_portfolio
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  timelines: ^0.1.0
  url_launcher: ^6.2.6
  velocity_x: ^4.1.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/dev.png
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Custom
      fonts:
        - asset: assets/Poppins-Regular.ttf
        - asset: assets/Poppins-Light.ttf
          weight: 400
        - asset: assets/Poppins-Medium.ttf
          weight: 600
        - asset: assets/Poppins-Bold.ttf
          weight: 800
        - asset: assets/Poppins-ExtraBold.ttf
          weight: 900
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
